{% set name = "flake8-use-pathlib" %}
{% set version = "0.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0ef19f255a51601bcf04ff54f25ef8a466dff68210cd95b4f1db36a78ace5223

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    # - poetry-core
    - poetry
    # Build-system is currently full Poetry.
    # See <https://gitlab.com/RoPP/flake8-use-pathlib/-/merge_requests/6>
  run:
    - python >=3.7
    - flake8 >=3.6

test:
  imports:
    - flake8_use_pathlib
  commands:
    - pip check
    - 'flake8 --version | grep flake8-use-pathlib:'
  requires:
    - pip

about:
  home: https://gitlab.com/RoPP/flake8-use-pathlib
  summary: A plugin for flake8 finding use of functions that can be replaced by pathlib module.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - maresb
