{% set name = "flake8-use-pathlib" %}
{% set version = "0.2.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 844023d3e1ed55dc183bfd5421c4887f1d8242a85f183d6b4849567da6f9ee5e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - poetry
  run:
    - dataclasses >=0.7,<0.8
    - flake8 >=3.8.3,<4.0.0
    - python >=3.6

test:
  imports:
    - flake8_use_pathlib
  commands:
    - pip check
    - 'flake8 --version | grep flake8-use-pathlib:'
  requires:
    - pip

about:
  home: https://gitlab.com/RoPP/flake8-use-pathlib
  summary: A plugin for flake8 finding use of functions that can be replaced by pathlib module.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - maresb
